#pragma once

// Normally, this header is generated by CMake in SDK.
// Here, always include rename_exceptions header and include "pico" board variant for reasonable defaults.

#include "boards/pico.h"
#include "cmsis/rename_exceptions.h"